package pkg

var Tmpl = `// Code generated by go generate; DO NOT EDIT.
package {{.Package}}

import (
	"encoding/json"
	{{range $key, $value := .Imports -}}
	{{renamedImport $value $key}} "{{$key}}"
	{{end -}}
	"stash.ovh.net/cloud/integration/pkg/domain/errors"
)

// Generated builder

{{range $structIndex, $struct := .Structs}}
type {{$struct.Name}}Builder struct {
	built {{$struct.Name}}
	setters []func(ctx context.Context)errors.StackError
}

func New{{$struct.Name}}() *{{$struct.Name}}Builder {
	return &{{$struct.Name}}Builder{
		built: {{$struct.Name}}{},
	}
}
{{range .Fields}}
func (builder *{{$struct.Name}}Builder) With{{toUpper (prettifyFieldName .Name)}}({{toLower .Name}} {{.Type}}) *{{$struct.Name}}Builder {
	builder.built.{{.Name}} = {{toLower .Name}}
	return builder
}

{{if .FromString}}
func (builder *{{$struct.Name}}Builder) With{{toUpper (prettifyFieldName .Name)}}String({{toLower .Name}} string) *{{$struct.Name}}Builder {
	builder.setters = append(builder.setters, func(ctx context.Context) errors.StackError {
		err := builder.built.{{.Name}}.FromString(ctx, {{toLower .Name}})
		if err != nil {
			return err.Infof("fail to build {{toLower .Name}} '%s' to type {{.Type}}", {{toLower .Name}})
		}
		return nil
	})
	return builder
}
{{end}}
{{end}}
func (builder *{{$struct.Name}}Builder) Build(ctx context.Context) ({{if $struct.Pointer}}*{{end}}{{$struct.Name}}, errors.StackError) {

	for _,setter := range builder.setters{
		err := setter(ctx)
		if err != nil {
			return {{if not $struct.Pointer}}{{$struct.Name}}{}{{else}}nil{{end}}, err
		}
	}

	if err := builder.built.validate(ctx); err != nil {
		return {{if not $struct.Pointer}}{{$struct.Name}}{}{{else}}nil{{end}}, err
	}

	return {{if $struct.Pointer}}&{{end}}builder.built, nil
}

func BuilderFrom{{$struct.Name}}({{toLower $struct.Name}} {{$struct.Name}}) *{{$struct.Name}}Builder {
	return New{{$struct.Name}}().
	{{- range $index, $value := .Fields}}
		With{{toUpper (prettifyFieldName $value.Name)}}({{toLower $struct.Name}}.{{$value.Name}}){{if ne (add $index 1) (len $struct.Fields)}}.{{end}}
	{{- end}}
}

// Generated getter
{{range .Fields}}
func ({{firstToLower $struct.Name}} {{$struct.Name}}) {{if .Optional}}Try{{end}}Get{{toUpper (prettifyFieldName .Name)}}() {{.Type}} {
	return {{firstToLower $struct.Name}}.{{.Name}}
}
{{end}}

// Generated JSON Marshal/Unmarshal

type {{toLower $struct.Name}} struct {
{{range .Fields -}}
	{{toUpper .Name}} {{.Type}} {{ .Tags}}
{{end}}
}
func ({{firstToLower $struct.Name}} {{$struct.Name}}) MarshalJSON() ([]byte, error) {
	bb, err := json.Marshal(&{{toLower $struct.Name}}{
		{{range .Fields -}}
		{{toUpper .Name}}: {{firstToLower $struct.Name}}.{{.Name}},
		{{end}}
	})
	if err != nil {
		return nil, errors.NewInternal(context.Background(), err)
	}

	return bb, nil
}

func ({{firstToLower $struct.Name}} *{{$struct.Name}}) UnmarshalJSON(data []byte) error {
	aux := &{{toLower $struct.Name}}{}
	if err := json.Unmarshal(data, &aux); err != nil {
		return errors.NewInvalid(context.Background(),err)
	}
	{{range .Fields -}}
	{{firstToLower $struct.Name}}.{{.Name}} = aux.{{toUpper .Name}}
	{{end}}

	type isZeroable interface {
		IsZero() bool
	}

	if iz, ok := interface{}({{firstToLower $struct.Name}}).(isZeroable); ok && iz.IsZero() {
		return nil
	}
	if err := {{firstToLower $struct.Name}}.validate(context.Background()); err != nil {
		return err
	}
	return nil
}
{{end}}
`
